package com.wag.qe.pact.provider;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;

import java.net.URL;

/**
 * Provider-side verification: Patient Service satisfying Prescription Service contracts.
 * Reads pact JSON from target/pacts/ (generated by PrescriptionConsumerTest).
 * In CI, pacts are fetched from the Pact Broker instead — swap @PactFolder for @PactBroker.
 */
@Provider("PatientService")
@PactFolder("target/pacts")
class PatientProviderTest {

    @BeforeEach
    void setUp(PactVerificationContext context) throws Exception {
        String baseUrl = System.getProperty("api.base.url", "https://jsonplaceholder.typicode.com");
        URL url = new URL(baseUrl);
        int port = url.getPort() == -1 ? (url.getProtocol().equals("https") ? 443 : 80) : url.getPort();
        context.setTarget(new HttpTestTarget(url.getHost(), port, url.getPath()));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPacts(PactVerificationContext context) {
        context.verifyInteraction();
    }
}
